name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ghcr.io/cmiles74/docker-mcp-servers:${{ github.event.release.tag_name }} -t ghcr.io/cmiles74/docker-mcp-servers:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish image
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: docker push ghcr.io/cmiles74/docker-mcp-servers:${{ github.event.release.tag_name }}; docker push ghcr.io/cmiles74/docker-mcp-servers:latest
